# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 817a63377a2b79c4c2f95407de3879823017e546e70362c78cd0e994b5ad3418095824e312b3e298a0f0ed0e377e5ce1144bf766a0b89eb59fd37347a1863c2e

test:
  secret_key_base: 49b2f884afa971415b2a07fdc20127f65e37357910fd7776bfad2f0a721d5f766239259f57defaac1208eee6e8163cb042bea147421ecf68b44152e0aa40e37b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
